-- init-h2.sql OBRIGATORIO para perfil LOCAL rodar entidades anotadas com schema = 'public'
-- e enums PostgreSQL nativos (MEDIA_TYPE, GENDER_TYPE etc) mapeados como @Enumerated(STRING).
-- O H2 em MODE=PostgreSQL NAO EXECUTA CREATE TYPE, ele mapeia via CREATE DOMAIN (como alias VARCHAR).
CREATE SCHEMA IF NOT EXISTS PUBLIC;
SET SCHEMA PUBLIC;
CREATE DOMAIN IF NOT EXISTS MEDIA_TYPE AS VARCHAR(255);
CREATE DOMAIN IF NOT EXISTS GENDER_TYPE AS VARCHAR(255);
CREATE DOMAIN IF NOT EXISTS SUBMISSION_GENDER AS VARCHAR(255);
CREATE DOMAIN IF NOT EXISTS CANDIDATE_STATUS AS VARCHAR(255);
CREATE DOMAIN IF NOT EXISTS ADMIN_ROLE AS VARCHAR(255);
CREATE DOMAIN IF NOT EXISTS SUBMISSION_STATUS AS VARCHAR(255);
CREATE DOMAIN IF NOT EXISTS CONTENT_SECTION_KEY AS VARCHAR(255);